title: <p align="center"> Geeta Desai</p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="www.linkedin.com/in/geeta-desai-94b514139/">LinkedIn</a> |
  <a href="https://github.com/sajankedia">GitHub</a>
  
  <br>   
  I'm working on Data Science, Chaos engineering and  Machine learning & NLP related problems.
 I am working with UBS 
  <br>
  </p>



theme: jekyll-theme-minimal
